In [4]:
import numpy as np

In [5]:
n1 = np.array([1,2,3,4,5,6])
n1

array([1, 2, 3, 4, 5, 6])

In [6]:
type(n1)

numpy.ndarray

In [7]:
n2 = np.array([[1,2,3,4,5,6],[10,20,30,40,50,60]])
n2

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [8]:
type(n2)

numpy.ndarray

In [9]:
import numpy as np

In [10]:
n3 = np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
n4 = np.zeros((6,6))
n4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
n5 = np.full((3,3),(5))
n5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [121]:
n6 = np.full((3,6),9)
n6

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [14]:
n7 = np.arange(10,51)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [15]:
n8 = np.arange(10,501,5)
n8

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
       140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200,
       205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265,
       270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320, 325, 330,
       335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385, 390, 395,
       400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450, 455, 460,
       465, 470, 475, 480, 485, 490, 495, 500])

In [16]:
n9 = np.random.randint(100,1000,10)
n9

array([973, 648, 180, 567, 390, 818, 947, 544, 543, 382])

In [17]:
n1.shape

(6,)

In [18]:
n10 = np.array([[1,2,3],[4,5,6]])
n10

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
n10.shape

(2, 3)

In [20]:
n10.shape = (3,2)
n10

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
n1 = np.array([10, 20,30])
n2 = np.array ([100,200,300])
np.vstack([n1,n2])
np.hstack([n1,n2])

array([ 10,  20,  30, 100, 200, 300])

In [22]:
np.column_stack((n1,n2))

array([[ 10, 100],
       [ 20, 200],
       [ 30, 300]])

In [29]:
import numpy as np
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])
np.intersect1d(n1,n2)

array([50, 60])

In [33]:
import numpy as np
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [34]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [46]:
import numpy as np
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90,100])
np.shape([n1])

(1, 6)

In [47]:
np.shape([n1])

(1, 6)

In [48]:
n1.shape

(6,)

In [49]:
np.shape(n1)

(6,)

In [53]:
n1 = np.array([[10,20],[30, 40]])
n1
n1.shape

(2, 2)

In [55]:
np.shape(n1)

(2, 2)

In [58]:
np.shape([n1])

(1, 2, 2)

In [60]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90,100])
np.sum([n1,n2])

660

In [61]:
np.sum([n1,n2], axis=0)

array([ 60,  80, 100, 120, 140, 160])

In [62]:
np.sum([n1,n2], axis=1)

array([210, 450])

In [87]:
n1

array([35, 45, 55, 65, 75, 85])

In [88]:
n1 = np.array([10, 20, 30, 40])
n1+100

array([110, 120, 130, 140])

In [92]:
n1=n1+100
n1

array([210, 220, 230, 240])

n1

In [93]:
n1

array([210, 220, 230, 240])

In [95]:
n1= np.array([10, 20, 30])
n1+100

array([110, 120, 130])

# 

In [96]:
n1-5

array([ 5, 15, 25])

In [97]:
n1 * 5

array([ 50, 100, 150])

In [98]:
n1 / 10

array([1., 2., 3.])

In [100]:
np.mean(n1)

20.0

In [124]:
n1 = np.array ([10,48,23,9,45,61])
n2=np.array ([30,40])

In [125]:
np.mean(n1)

32.666666666666664

In [126]:
np.std(n1)

19.821424996424675

In [127]:
np.median(n1)

34.0

In [132]:
np.save('my_numpy',n1)

In [134]:
n2= np.load('my_numpy.npy')
n2

array([10, 48, 23,  9, 45, 61])